/run/setCut 1 um
/run/numberOfThreads 12
/run/initialize
/control/verbose 1 		# max 2
/run/verbose 1 			# max 2
/event/verbose 0		# max 2
/tracking/verbose 0 	# max 5
/analysis/ntuple/setActivationToAll  true
#
/random/setSeeds 5463285 7562145
/run/printProgress 100000
#
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/DataSet_3/data10M
/generator/momentum/SetRandom true
/generator/momentum/SetRandomMinValue 1.0
/generator/momentum/SetRandomMaxValue 3.5
/run/beamOn 10000000