/run/setCut 1 um
/run/initialize
/control/verbose 1 		# max 2
/run/verbose 0 			# max 2
/event/verbose 0		# max 2
/tracking/verbose 0 	# max 5
/analysis/ntuple/setActivationToAll  true
#
/random/setSeeds 5463285 7562145
/run/printProgress 100000
#/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_20
#
/generator/momentum/SetRandom false
#
/generator/momentum/SetMomentum 0.0
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_0
/run/beamOn 500000
/generator/momentum/SetMomentum 39.19081
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_1
/run/beamOn 500000
/generator/momentum/SetMomentum 19.59615
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_2
/run/beamOn 500000
/generator/momentum/SetMomentum 13.06493
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_3
/run/beamOn 500000
/generator/momentum/SetMomentum 9.79957
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_4
/run/beamOn 500000
/generator/momentum/SetMomentum 7.84055
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_5
/run/beamOn 500000
/generator/momentum/SetMomentum 6.5347
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_6
/run/beamOn 500000
/generator/momentum/SetMomentum 5.6021
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_7
/run/beamOn 500000
/generator/momentum/SetMomentum 4.90277
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_8
/run/beamOn 500000
/generator/momentum/SetMomentum 4.35896
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_9
/run/beamOn 500000
/generator/momentum/SetMomentum 3.92401
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_10
/run/beamOn 500000
/generator/momentum/SetMomentum 3.56823
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_11
/run/beamOn 500000
/generator/momentum/SetMomentum 3.27184
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_12
/run/beamOn 500000
/generator/momentum/SetMomentum 3.02112
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_13
/run/beamOn 500000
/generator/momentum/SetMomentum 2.80628
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_14
/run/beamOn 500000
/generator/momentum/SetMomentum 2.62016
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_15
/run/beamOn 500000
/generator/momentum/SetMomentum 2.45737
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_16
/run/beamOn 500000
/generator/momentum/SetMomentum 2.31379
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_17
/run/beamOn 500000
/generator/momentum/SetMomentum 2.18622
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_18
/run/beamOn 500000
/generator/momentum/SetMomentum 2.07213
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_19
/run/beamOn 500000
/generator/momentum/SetMomentum 1.9695
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_20
/run/beamOn 500000
/generator/momentum/SetMomentum 1.87669
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_21
/run/beamOn 500000
/generator/momentum/SetMomentum 1.79237
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_22
/run/beamOn 500000
/generator/momentum/SetMomentum 1.71542
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_23
/run/beamOn 500000
/generator/momentum/SetMomentum 1.64493
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_24
/run/beamOn 500000
/generator/momentum/SetMomentum 1.58012
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_25
/run/beamOn 500000
/generator/momentum/SetMomentum 1.52033
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_26
/run/beamOn 500000
/generator/momentum/SetMomentum 1.46501
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_27
/run/beamOn 500000
/generator/momentum/SetMomentum 1.41368
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_28
/run/beamOn 500000
/generator/momentum/SetMomentum 1.36592
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_29
/run/beamOn 500000
/generator/momentum/SetMomentum 1.32139
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_30
/run/beamOn 500000
#/generator/momentum/SetRandom true
#/generator/momentum/SetRandomMinValue 1.5
#/generator/momentum/SetRandomMaxValue 2.5
#