/run/setCut 1 um
/run/initialize
/control/verbose 1 		# max 2
/run/verbose 0 			# max 2
/event/verbose 0		# max 2
/tracking/verbose 0 	# max 5
/analysis/ntuple/setActivationToAll  true
#
/random/setSeeds 5463285 7562145
/run/printProgress 100000
#
/generator/gun/pT 1.6
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_1
/run/beamOn 1000000
/generator/gun/pT 1.63
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_2
/run/beamOn 1000000
/generator/gun/pT 1.66
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_3
/run/beamOn 1000000
/generator/gun/pT 1.69
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_4
/run/beamOn 1000000
/generator/gun/pT 1.72
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_5
/run/beamOn 1000000
/generator/gun/pT 1.75
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_6
/run/beamOn 1000000
/generator/gun/pT 1.78
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_7
/run/beamOn 1000000
/generator/gun/pT 1.81
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_8
/run/beamOn 1000000
/generator/gun/pT 1.84
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_9
/run/beamOn 1000000
/generator/gun/pT 1.87
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_10
/run/beamOn 1000000
/generator/gun/pT 1.9
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_11
/run/beamOn 1000000
/generator/gun/pT 1.93
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_12
/run/beamOn 1000000
/generator/gun/pT 1.96
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_13
/run/beamOn 1000000
/generator/gun/pT 1.99
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_14
/run/beamOn 1000000
/generator/gun/pT 2.02
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_15
/run/beamOn 1000000
/generator/gun/pT 2.05
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_16
/run/beamOn 1000000
/generator/gun/pT 2.08
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_17
/run/beamOn 1000000
/generator/gun/pT 2.11
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_18
/run/beamOn 1000000
/generator/gun/pT 2.14
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_19
/run/beamOn 1000000
/generator/gun/pT 2.17
/analysis/setFileName /media/matthieu/ssd1/Geant4/Data/test_20
/run/beamOn 1000000
#
# /analysis/setFileName B5_proton